spring:
    application:
        name: syncfilekafka

MICROSOFT_DB_USERNAME: sa
MICROSOFT_DB_PASSWORD: 123456a@@
FS_US: administrator
FS_PW: Fbo@123
FS_DM: MITALAB


ds:
    ma:
        name: MADataSource
        jdbcUrl: jdbc:sqlserver://192.168.100.53\sql2014;database=MinhAn_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        maximumPoolSize: 1
        host: "192.168.100.53"
        connectShare: "MinhAn"
        fsUs: ${FS_US}
        fsPw: ${FS_PW}
        fsDM: ${FS_DM}
    maTest:
        name: MATestDataSource
        jdbcUrl: jdbc:sqlserver://192.168.100.53\sql2014;database=MinhAn_Test_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        maximumPoolSize: 1
        host: "192.168.100.53"
        connectShare: "MinhAn ERP"
        fsUs: ${FS_US}
        fsPw: ${FS_PW}
        fsDM: ${FS_DM}
    na:
        name: NADataSource
        jdbcUrl: jdbc:sqlserver://192.168.60.17\sql2014;database=NhatAnh_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        host: "192.168.60.17"
        connectShare: "nhatanh"
        fsUs: ${FS_US}
        fsPw: ${FS_PW}
        fsDM: ${FS_DM}
    np:
        name: NPDataSource
        jdbcUrl: jdbc:sqlserver://192.168.5.11\sql2014;database=NamPhuong_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        host: "192.168.5.11"
        connectShare: "NamPhuong"
        fsUs: ${FS_US}
        fsPw: ${FS_PW}
        fsDM: ${FS_DM}     
    sk:
        name: SKDataSource
        jdbcUrl: jdbc:sqlserver://10.0.20.11\sql2014;database=SKMT_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        host: "10.0.20.11"
        connectShare: "skmt"
        fsUs: ${FS_US}
        fsPw: ${FS_PW}
        fsDM: ${FS_DM}   
    tb:
        name: TBDataSource
        jdbcUrl: jdbc:sqlserver://192.168.100.51\sql2014;database=MinhTam_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        host: "192.168.100.51"
        connectShare: "minhtam"
        fsUs: ${FS_US}
        fsPw: ${FS_PW}
        fsDM: ${FS_DM}   
    cnmt:
        name: CNMTDataSource
        jdbcUrl: jdbc:sqlserver://192.168.10.47\sql2014;database=MinhTamHCM_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        host: "192.168.10.47"
        connectShare: "minhtamhcm"
        fsUs: ${FS_US}
        fsPw: ${FS_PW} 
        fsDM: ${FS_DM}  
    ha:
        name: HADataSource
        jdbcUrl: jdbc:sqlserver://192.168.60.16\sql2014;database=HongAnh_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        host: "192.168.60.16"
        connectShare: "HongAnh"
        fsUs: ${FS_US}
        fsPw: ${FS_PW}
        fsDM: ${FS_DM}   
    hn:
        name: HNDataSource
        jdbcUrl: jdbc:sqlserver://192.168.60.18\sql2014;database=HaiNam_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        host: "192.168.60.18"
        connectShare: "HaiNam"
        fsUs: ${FS_US}
        fsPw: ${FS_PW}
        fsDM: ${FS_DM}   
    th:
        name: THDataSource
        jdbcUrl: jdbc:sqlserver://192.168.60.12\sql2014;database=ThanhHa_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        host: "192.168.60.12"
        connectShare: "ThanhHa"
        fsUs: ${FS_US}
        fsPw: ${FS_PW}
        fsDM: ${FS_DM}
    ctdm:
        name: CTDMDataSource
        jdbcUrl: jdbc:sqlserver://10.0.10.16\sql2014;database=DuyMinhHCM_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        host: "10.0.10.16"
        connectShare: "DuyMinhHCM"
        fsUs: ${FS_US}
        fsPw: ${FS_PW}
        fsDM: ${FS_DM}
    lkdc:
        name: LKDCDataSource
        jdbcUrl: jdbc:sqlserver://192.168.60.15\sql2014;database=LKDC_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        host: "192.168.60.15"
        connectShare: "lkdc"
        fsUs: ${FS_US}
        fsPw: ${FS_PW}
        fsDM: ${FS_DM}

app:
    config:
        replaceController: {"Item_core": "Item"}
        overrideOptions: '1' ## co ghi de k?
        ignoreStatus: '1'
        timeout: 30
        appendable: false
        maPathFile: Upload\MinhAn_App
        maTestPathFile: Upload\MINHAN_Test_App
        npPathFile: Upload\NamPhuong_App
        naPathFile: Upload\NhatAnh_App
        skPathFile: Upload\SKMT_App
        tbPathFile: Upload\MinhTam_App
        cnmtPathFile: MINHTAMHCM_App
        ctdmPathFile: Upload\DuyMinhHCM_App
        thPathFile: Upload\THANHHA_App
        hnPathFile: Upload\HAINAM_App
        haPathFile: Upload\HongAnh_App
        lkdcPathFile: Upload\LKDC_App
        sendErrorIds: 64
        logDebugged: false
        kafka:
          bootstrapServer: 192.168.100.52:9092
          groupIdConsumer: listen1
          autoOffsetReset: earliest
          lingerMs: 10
          consumerMessageTopic: ""
          consumerMessageTopicPattern: ".*?dbo.sysfileoutbox"
          errorMessageTopic: "syncfileserror"
          enableAutoCommit: true
          autoCommitIntervalMs: 1000
        