spring:
    application:
        name: syncfilekafka

MICROSOFT_DB_USERNAME: sa
MICROSOFT_DB_PASSWORD: 123456a@@

ds:
    ma:
        name: MADataSource
        jdbcUrl: jdbc:sqlserver://192.168.100.53\sql2014;database=MinhAn_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        maximumPoolSize: 1
    maTest:
        name: MATestDataSource
        jdbcUrl: jdbc:sqlserver://192.168.100.53\sql2014;database=MinhAn_Test_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        maximumPoolSize: 1
    na:
        name: NADataSource
        jdbcUrl: jdbc:sqlserver://192.168.60.17\sql2014;database=NhatAnh_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    np:
        name: NPDataSource
        jdbcUrl: jdbc:sqlserver://192.168.5.11\sql2014;database=NamPhuong_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect        
    sk:
        name: SKDataSource
        jdbcUrl: jdbc:sqlserver://10.0.20.11\sql2014;database=SKMT_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    tb:
        name: TBDataSource
        jdbcUrl: jdbc:sqlserver://192.168.100.51\sql2014;database=MinhTam_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    cnmt:
        name: CNMTDataSource
        jdbcUrl: jdbc:sqlserver://192.168.10.47\sql2014;database=MinhTamHCM_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    ha:
        name: HADataSource
        jdbcUrl: jdbc:sqlserver://192.168.60.16\sql2014;database=HongAnh_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hn:
        name: HNDataSource
        jdbcUrl: jdbc:sqlserver://192.168.60.18\sql2014;database=HaiNam_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    th:
        name: THDataSource
        jdbcUrl: jdbc:sqlserver://192.168.60.12\sql2014;database=ThanhHa_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    ctdm:
        name: CTDMDataSource
        jdbcUrl: jdbc:sqlserver://10.0.10.16\sql2014;database=DuyMinhHCM_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    lkdc:
        name: LKDCDataSource
        jdbcUrl: jdbc:sqlserver://192.168.60.15\sql2014;database=LKDC_App;encrypt=True;trustServerCertificate=True;
        username: ${MICROSOFT_DB_USERNAME}
        password: ${MICROSOFT_DB_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dialect: org.hibernate.dialect.SQLServer2012Dialect

app:
    config:
        overrideOptions: '1' ## co ghi de k?
        ignoreStatus: '1'
        timeout: 30
        appendable: false
        maPathFile: \\192.168.100.53\MinhAn\Upload\MinhAn_App
        maTestPathFile: \\192.168.100.53\MinhAn ERP\Upload\MINHAN_Test_App
        npPathFile: \\192.168.5.11\NamPhuong\Upload\NamPhuong_App
        naPathFile: \\192.168.60.17\NHATANH\Upload\NhatAnh_App
        skPathFile: \\10.0.20.11\SKMT\Upload\SKMT_App
        tbPathFile: \\192.168.100.51\MINHTAM\Upload\MinhTam_App
        cnmtPathFile: \\192.168.10.47\MINHTAMHCM\Upload\MINHTAMHCM_App
        ctdmPathFile: \\10.0.10.16\DuyMinhHCM\Upload\DuyMinhHCM_App
        thPathFile: \\192.168.60.12\ThanhHa\Upload\THANHHA_App
        hnPathFile: \\192.168.60.18\HaiNam\Upload\HAINAM_App
        haPathFile: \\192.168.60.16\HongAnh\Upload\HongAnh_App
        lkdcPathFile: \\192.168.60.15\lkdc\Upload\LKDC_App
        sendErrorIds: 64
        logDebugged: false
        kafka:
          bootstrapServer: 192.168.100.52:9092
          groupIdConsumer: listen1
          autoOffsetReset: earliest
          lingerMs: 10
          consumerMessageTopic: ""
          consumerMessageTopicPattern: ".*?dbo.sysfileoutbox"
          errorMessageTopic: "syncfileserror"
          enableAutoCommit: true
          autoCommitIntervalMs: 1000
        